name: 'PHP STatic ANalyser (phpstan)'
description: 'PHPSTAN run'
author: 'David Lumaye (chindit)'
branding:
    icon: 'zap'
    color: 'green'
inputs:
    arguments:
        description: 'Arguments to add to PHPStan CLI'
        required: false
        default: ''
    bin:
        description: 'Which PHPStAN binary to use.'
        required: false
        default: '/phpstan'
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.bin }}
        - ${{ inputs.arguments }}
